-- bjmbc.ACCESS definition
use `bjmbc`;

CREATE TABLE `ACCESS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(50) NOT NULL,
  `PASSWORD` varchar(50) NOT NULL,
  `FAILED_ATTEMPTS` tinyint(4) DEFAULT NULL,
  `ACCOUNT_LOCKED` tinyint(4) DEFAULT NULL,
  `LOCK_TIME` datetime DEFAULT NULL,
  `ACCESS_TYPE` varchar(15) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.CENTRAL_ACCOUNT definition

CREATE TABLE `CENTRAL_ACCOUNT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_NAME` varchar(50) NOT NULL,
  `REVENUE_ACCOUNT_HASH` varchar(64) DEFAULT NULL,
  `AMOUNT` decimal(8,2) NOT NULL,
  `EXPENSE_ACCOUNT_HASH` varchar(64) DEFAULT NULL,
  `TRANSACTION_DATE` datetime NOT NULL DEFAULT current_timestamp(),
  `REVENUE_CATEGORY` varchar(45) NOT NULL,
  `EXPENSE_CATEGORY` varchar(45) NOT NULL,
  `YEAR` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.EXPENSE_CATEGORY definition

CREATE TABLE `EXPENSE_CATEGORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXPENSE_CATEGORY` varchar(45) NOT NULL,
  `YEAR` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=105 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.EXPENSE_PARTY definition

CREATE TABLE `EXPENSE_PARTY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(90) NOT NULL,
  `ORGANISATION` varchar(45) NOT NULL,
  `MEMORABLE_DATE` date NOT NULL,
  `OWNER_ADHAAR_NUMBER` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `PARTY_HASH` varchar(64) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.REVENUE_CATEGORY definition

CREATE TABLE `REVENUE_CATEGORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `YEAR` int(11) DEFAULT NULL,
  `REVENUE_CATEGORY` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=145 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.REVENUE_PARTY definition

CREATE TABLE `REVENUE_PARTY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(75) NOT NULL,
  `MEMORABLE_DATE` date NOT NULL,
  `ORGANISATION` varchar(75) NOT NULL,
  `OWNER_ADHAAR_NUMBER` char(20) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `PARTY_HASH` varchar(64) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.REVENUE_ALLOCATION definition

CREATE TABLE `REVENUE_ALLOCATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `YEAR` int(11) NOT NULL,
  `CATEGORY` varchar(45) NOT NULL,
  `ALLOCATION` decimal(8,2) NOT NULL,
  `PERCENT_ALLOCATION` decimal(2,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.REVENUE_ACCOUNT_TRANSACTION definition

CREATE TABLE `REVENUE_ACCOUNT_TRANSACTION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MONEY_IN` decimal(10,0) DEFAULT NULL,
  `MONEY_OUT` decimal(10,0) DEFAULT NULL,
  `YEAR` int(11) NOT NULL,
  `YTD_BALANCE` decimal(10,0) NOT NULL,
  `REVENUE_ACCOUNT_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.EXPENSE_ACCOUNT_TRANSFER definition

CREATE TABLE `EXPENSE_ACCOUNT_TRANSFER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXPENSE_ACCOUNT_ID` int(11) NOT NULL,
  `CENTRAL_ACCOUNT_ID` int(11) NOT NULL,
  `MONEY_IN` decimal(10,0) NOT NULL,
  `TRANSACTION_TIME` datetime NOT NULL,
  `MONEY_OUT` decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.REVENUE_ACCOUNT_TRANSFERS definition

CREATE TABLE `REVENUE_ACCOUNT_TRANSFERS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REVENUE_ACCOUNT_ID` int(11) NOT NULL,
  `CENTRAL_ACCOUNT_ID` int(11) NOT NULL,
  `MONEY_IN` decimal(10,0) DEFAULT NULL,
  `MONEY_OUT` decimal(10,0) DEFAULT NULL,
  `TRANSACTION_TIME` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.EXPENSE_ALLOCATION definition

CREATE TABLE `EXPENSE_ALLOCATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `YEAR` int(11) NOT NULL,
  `CATEGORY` varchar(45) NOT NULL,
  `ALLOCATION` decimal(10,0) NOT NULL,
  `PERCENT_ALLOCATION` decimal(10,0) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.EXPENSE_ACCOUNT definition

CREATE TABLE `EXPENSE_ACCOUNT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) NOT NULL,
  `EXPENSE_PARTY_ID` bigint(20) NOT NULL,
  `EXPENSE_ACCOUNT_HASH` varchar(64) NOT NULL,
  `EXPENSE_CATEGORY_ID` int(11) NOT NULL,
  `CREATED_ON` timestamp NOT NULL,
  PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- bjmbc.REVENUE_ACCOUNT definition

CREATE TABLE `REVENUE_ACCOUNT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `REVENUE_ACCOUNT_HASH` varchar(64) NOT NULL,
  `REVENUE_CATEGORY_ID` int(11) NOT NULL,
  `REVENUE_PARTY_ID` bigint(20) NOT NULL,
  `CREATED_ON` timestamp NOT NULL,
  PRIMARY KEY (`ID`)
  ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;